
public enum ClaseLexica {
	IDEN, PAP, PCIERRE, ASIG, COMA, 
	MAS, MENOS, POR, DIV, EVAL, EOF, 
	
	MENOSU,	GT, GE, LT, LE, EQ, NE, PYC, LLAP, LLCIERRE, SEP, E,
	
	TRUE, FALSE, AND, OR, NOT, BOOL,ENT, REAL
}
