
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package c_ast_ascendente;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEP = 9;
  public static final int POR = 36;
  public static final int LLCIERRE = 8;
  public static final int GE = 39;
  public static final int CCIERRE = 15;
  public static final int CIRCUNFLEJO = 48;
  public static final int PCIERRE = 3;
  public static final int LITERALREAL = 50;
  public static final int CAP = 52;
  public static final int DELETE = 26;
  public static final int WRITE = 28;
  public static final int NOT = 47;
  public static final int AND = 45;
  public static final int LT = 40;
  public static final int LLAP = 7;
  public static final int TYPE = 30;
  public static final int OR = 46;
  public static final int EVAL = 5;
  public static final int BOOL = 12;
  public static final int CALL = 31;
  public static final int LITERALCADENA = 51;
  public static final int DIV = 37;
  public static final int IF = 21;
  public static final int LE = 41;
  public static final int EOF = 0;
  public static final int ASIG = 33;
  public static final int AMP = 17;
  public static final int TRUE = 10;
  public static final int NEW = 25;
  public static final int error = 1;
  public static final int COMA = 4;
  public static final int MENOS = 35;
  public static final int NULL = 19;
  public static final int MOD = 44;
  public static final int EQ = 42;
  public static final int REAL = 14;
  public static final int ENT = 13;
  public static final int PAP = 2;
  public static final int ELSE = 22;
  public static final int PUNTO = 16;
  public static final int NL = 29;
  public static final int READ = 27;
  public static final int IDEN = 32;
  public static final int WHILE = 23;
  public static final int NE = 43;
  public static final int PROC = 20;
  public static final int STRING = 18;
  public static final int FALSE = 11;
  public static final int STRUCT = 24;
  public static final int GT = 38;
  public static final int LITERALENTERO = 49;
  public static final int PYC = 6;
  public static final int MAS = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PAP",
  "PCIERRE",
  "COMA",
  "EVAL",
  "PYC",
  "LLAP",
  "LLCIERRE",
  "SEP",
  "TRUE",
  "FALSE",
  "BOOL",
  "ENT",
  "REAL",
  "CCIERRE",
  "PUNTO",
  "AMP",
  "STRING",
  "NULL",
  "PROC",
  "IF",
  "ELSE",
  "WHILE",
  "STRUCT",
  "NEW",
  "DELETE",
  "READ",
  "WRITE",
  "NL",
  "TYPE",
  "CALL",
  "IDEN",
  "ASIG",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "NE",
  "MOD",
  "AND",
  "OR",
  "NOT",
  "CIRCUNFLEJO",
  "LITERALENTERO",
  "LITERALREAL",
  "LITERALCADENA",
  "CAP"
  };
}

